- build.xml
Fix for dev build target so we can work on non-feature zimbra instance without manually copying them in.
These need to be added to the zm-build/zcs-lib changes too in ZCS-3349's PR.
> ZCS-5118 Add jackson jars on deploy.

- src/java-test/com/zimbra/oauth/handlers/impl/GoogleContactsImportTest.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleOAuth2Handler.java
* Added support for Google contact import. Follows structure of the Yahoo version.
* As requested in the discussion chain:
* Only creates new contacts
* "New" is defined as a contact which does not have an associated contact (determined by `resourceName` property added to the contact) in the datasource folder at the time of the sync - seeking opinions on this determination method
* Does not delete/modify existing contacts
* See JIRA ticket for omitted properties (ageRanges, gender, relations, etc). Open for discussion if any of these are necessary immediately.
> ZCS-5095 Added google contacts importer.

- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/utilities/LdapConfiguration.java
The API  scope attribute can also be a URI(so can contain":", hence modified the parsing of zimbraOAuthConsumerAPIScope.
Added logging for improving debugging
> ZCS-5109 Add logging and fix parsing of api scope attr

- src/java/com/zimbra/oauth/handlers/impl/GoogleContactsImport.java
When importing contacts if the scope is not defined correctly or the library is not added to the credentials, the import will return error. 
Added code to throw an exception if the import fails and return error.
Verified by removing the API scope  attribute and importing contacts, the import failed and and exception was recorded in the logs.
> ZCS-5095 Added code to throw exception for error resp

- src/java-test/com/zimbra/oauth/handlers/impl/FacebookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/GoogleOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/OutlookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/YahooOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/managers/ClassManagerTest.java
- src/java-test/com/zimbra/oauth/utilities/OAuth2ResourceUtilitiesTest.java
- src/java/com/zimbra/oauth/handlers/IOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/FacebookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OutlookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/YahooOAuth2Handler.java
- src/java/com/zimbra/oauth/utilities/OAuth2Constants.java
- src/java/com/zimbra/oauth/utilities/OAuth2ResourceUtilities.java
- src/java/com/zimbra/oauth/utilities/OAuth2Utilities.java
Looking for commentary.
* Fetch profile images for Google and Yahoo.
* Created with a default attachment name - if relevant can be found in yahoo/google constants
* Yahoo does not appear to allow adding new contact images, unless I am missing something, so this functionality may only be supporting legacy contacts (pure speculation here).
* Create contacts and clear/free ParsedContact references every 100 contacts for Google
* Not able to do this for Yahoo due to the way the `sync` style contact listing works, but I believe it is in our best interest to use that method since Yahoo will handle determining what is new for us - so after much testing with it I am leaving Yahoo as is.
Outlook should follow the same format given some contact api features.
> Zcs 5201 Profile image fetch on contact import

- src/java-test/com/zimbra/oauth/utilities/OAuth2ResourceUtilitiesTest.java
- src/java/com/zimbra/oauth/handlers/IOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/utilities/OAuth2ResourceUtilities.java
Problem: error code 400 is shown on browser when user clicks on "NOT NOW" button on authentication screen on yahoo/google
Fix:
1. relay param in authenticate is needed. so keep it even if there is no value in relay.
2. renamed verifyAuthenticateParams to verifyAndSplitAuthenticateParams.
3. added constant for relay delimiter.
Testing Done:
1. tested functionality manually both positive and negative with yahoo.
Testing to be done by QA:
1. test functionality both positive and negative cases with yahoo/google/facebook
> ZCS-4961 fixing failure on clicking not now on authentication

- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooOAuth2Handler.java
**Problem:** if relay is not provided in url and not now is clicked on authentication page, 400 error is shown on browser.
**Fix:** 1st split relay and then check for error in authentication.
**Testing done:** Tested functionality manually on yahoo with and without relay.
> ZCS-4961 fixing 400 failure when pressed not now without relay in url

- src/java/com/zimbra/oauth/handlers/impl/FacebookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OutlookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooOAuth2Handler.java
* Using `fromString` to get an enum instance for the validation switch cases.
> ZCS-5172 Use fromString for error switch.

- src/java/com/zimbra/oauth/handlers/IOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooOAuth2Handler.java
- src/java/com/zimbra/oauth/resources/ZOAuth2Servlet.java
- src/java/com/zimbra/oauth/utilities/OAuth2ErrorConstants.java
- src/java/com/zimbra/oauth/utilities/OAuth2ResourceUtilities.java
We used failure during 4961, just editing to show a more helpful message when missing the `type` param. Won't handle logging cleanup for all the handlers in this ticket.
* Show invalid request when missing type param
> ZCS-5411 Fix unhandled error when missing type param

- src/java/com/zimbra/oauth/handlers/impl/FacebookContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooContactsImport.java
Removes private information, like access tokens, from showing up in the logs.
> ZCS-5331 Removes token information from the logs.

- src/java-test/com/zimbra/oauth/handlers/impl/OutlookContactsImportTest.java
- src/java/com/zimbra/oauth/handlers/impl/GoogleContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OutlookContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/OutlookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooContactsImport.java
- src/java/com/zimbra/oauth/utilities/OAuth2Utilities.java
Adding support for Outlook contacts import.
* Basic properties supported see Jira ZCS-5197 for list (note this is about 95% of them)
* Imports profile images
* Moved some `HttpClient` methods to utilities for ease of sharing
* Reusing a proxy configured `HttpClient` instance for every chunk of contacts profile images we fetch in blocks of 100
* Outlook API docs states they only support full sync so "new change-only" fetches are not feasible. This causes contacts that have been deleted locally to be re-imported during sync.
* Root contact folder and top level folder contacts are imported
* In theory it is possible to create non-root sub-sub-folders but I am unable to do this in the Outlook UI so I have opted to remove BFS implementation and just do as stated in primary bullet.
* Product …
> ZCS-5197 Support Outlook contacts import

- src/java-test/com/zimbra/oauth/handlers/impl/FacebookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/GoogleOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/OutlookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/YahooOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/utilities/OAuth2ResourceUtilitiesTest.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/models/OAuthInfo.java
- src/java/com/zimbra/oauth/resources/ZOAuth2Servlet.java
- src/java/com/zimbra/oauth/utilities/OAuth2ErrorConstants.java
- src/java/com/zimbra/oauth/utilities/OAuth2HttpConstants.java
- src/java/com/zimbra/oauth/utilities/OAuth2ResourceUtilities.java
- src/java/com/zimbra/oauth/utilities/OAuth2Utilities.java
Per discussion, I went with option 1 on the jira ticket - implementing via the state parameter.
A JWT is searched for via the `Authorization` header on the `authorize` request. The encoded token is appended to the `state` relay sent to the social service and bounced back to the `authenticate` callback where is it checked for in the returning `state` relay, before the usual places are checked (headers, cookies).
* Basic JWT support for all clients
* Priority given to jwt, falling back to cookies if none
* Moved authentication logic from servlet class into the resource class for ease of access since relay parsing requires some assistance from the handlers due to some clients having odd key names (e.g. twitter).
* Replaced servlet exceptions because we weren't handling redirect for them, …
> ZCS-4924 Add support for JWT auth.

- src/java/com/zimbra/oauth/utilities/OAuth2Constants.java
- src/java/com/zimbra/oauth/utilities/OAuth2DataSource.java
* Add client identifier to ds folder name.
Resolves issues for clients with ambiguous user identifiers.
See ticket for details.
> ZCS-5596 Add client identifier to ds folder name.

- src/java/com/zimbra/oauth/utilities/OAuth2ResourceUtilities.java
* Fix NPE on unauthenticated request
Logged out state on the `authorize` url results in an NPE. Does not affect regular flow.
See ticket for details.
> ZCS-5594 Possible NPE on unauthenticated request.

- README.md
- src/java-test/com/zimbra/oauth/handlers/impl/FacebookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/GoogleOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/OutlookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/YahooOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/managers/ClassManagerTest.java
- src/java/com/zimbra/oauth/handlers/impl/FacebookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/utilities/OAuth2ConfigConstants.java
* Fetch soap service uri from account for ZMailbox creation to resolve multi-node env issue.
Tested in aws and local for mutli and single.
> ZCS-5599 Use request account's soap service uri

- src/java-test/com/zimbra/oauth/handlers/impl/FacebookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/GoogleOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/OutlookOAuth2HandlerTest.java
- src/java-test/com/zimbra/oauth/handlers/impl/TwitterOAuth2HandlerTest.java
- src/java/com/zimbra/oauth/handlers/impl/FacebookOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/OAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/TwitterContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/TwitterOAuth2Handler.java
- src/java/com/zimbra/oauth/utilities/OAuth2ResourceUtilities.java
* Added Twitter ds handler.
* Stores token as `<token>::<secret>` since we need both pieces to sign requests to all twitter APIs.
* Added twitter auth header builder for use when requesting to twitter APIs. (see example in authorize or authenticate - similar procedure for other services, just add `withParam` for anything that needs to be added to the signature).
* No-op twitter importer.
* Moved some relay parsing and param validation into separate methods to reduce code necessary for twitter handler.
Please note that Twitter auth is 3-legged, and that success response is a tokenized string, whereas errors are in json format.
Looking for feedback.
> ZCS-2694 Create DataSource implementation for Twitter contacts via oAuth

- src/java-test/com/zimbra/oauth/handlers/impl/TwitterContactsImportTest.java
- src/java/com/zimbra/oauth/handlers/impl/TwitterContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/TwitterOAuth2Handler.java
- src/java/com/zimbra/oauth/utilities/OAuth2DataSource.java
Add support for twitter contacts import.
* Import basic properties outlined in jira ticket
* No profile image, or excess rate limit handling
* Will not be handling that functionality due to lack of email address accessibility rendering these "contacts" superficial
* Current behavior is logged error and an exception on rate limit exceed
**Testing Done**
* General authorization flow with a test twitter account
* Contact Datasource import
* Pagination tests
* Imported basic properties
**Testing to be done by QA**
* Generic contact import tests as defined by other services on testrail
> ZCS-5476 Support Twitter contacts import.

- README.md
- src/java/com/zimbra/oauth/handlers/impl/GoogleContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/OutlookContactsImport.java
- src/java/com/zimbra/oauth/handlers/impl/TwitterOAuth2Handler.java
- src/java/com/zimbra/oauth/handlers/impl/YahooContactsImport.java
- src/java/com/zimbra/oauth/models/HttpResponseWrapper.java
- src/java/com/zimbra/oauth/utilities/CalDavOAuth2Client.java
- src/java/com/zimbra/oauth/utilities/OAuth2Utilities.java
* Fix an issue where pre-emptively closing the request connection in `executeRequestRaw` prevents completion of entity stream read in subsequent methods - resulting in truncated chunk exception.
* Read entity before closing request then use http response wrapper to store raw closed response and entity bytes where appropriate
* Use improved `EntityUtils` for entity read
* Removed some unnecessary config from caldav client
* Updated readme with some missing/outdated config (no user facing change)
**Testing Done**
Tested contact import on vm003/011 with outlook and google (including caldav for google)
**Testing to be Done by QA**
See jira. Cal sync, other clients etc.
> ZCS-7167 Fix http entity reading before request closure.

- build.xml
Issue: Third party vulnerabilities in Jackson library
Fix: Upgrade the Jackson library to the latest version
Related PRs:
https://github.com/Zimbra/zm-mailbox/pull/984
https://github.com/Zimbra/zm-zcs-lib/pull/59
https://github.com/Zimbra/zm-gql/pull/54
https://github.com/Zimbra/zm-gql-admin/pull/1
https://github.com/Zimbra/zm-network-gql/pull/5
> ZCS-8011: Third party vulnerabilities in Jackson databind

- eclipse-ivysettings.xml
- src/java/com/zimbra/oauth/resources/ZOAuth2ProxyServlet.java
- src/java/com/zimbra/oauth/utilities/OAuth2ProxyUtilities.java
* Allow Patch proxying to support Zoom meeting modifications.
* Fix a copy error when body is empty; can't be null.
* Add dom4j to local ivysettings copy.
Depends on:
Zimbra/zm-mailbox#1044
> ZCS-8911 Allow HTTP Patch proxying.
